
import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Download, Loader2 } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { toast } from 'sonner';

export default function ExportPDFButton({ patientName, patientId, therapistName, date, soapData, clinicName = "Physiome Clinic" }) {
  const [isExporting, setIsExporting] = useState(false);

  const handleExport = async () => {
    setIsExporting(true);
    
    try {
      // Simulate slight delay for library loading/processing
      await new Promise(r => setTimeout(r, 500));
      
      const doc = new jsPDF();
      
      // Header
      doc.setFontSize(20);
      doc.setTextColor(37, 99, 235); // Primary blue
      doc.text(clinicName, 20, 20);
      
      doc.setFontSize(16);
      doc.setTextColor(30, 41, 59); // Slate 800
      doc.text("Clinical SOAP Note", 20, 32);
      
      // Meta Information
      doc.setFontSize(10);
      doc.setTextColor(71, 85, 105); // Slate 600
      doc.text(`Patient: ${patientName || 'Unknown Patient'}`, 20, 45);
      if (patientId) doc.text(`Patient ID: ${patientId}`, 20, 52);
      doc.text(`Date of Visit: ${new Date(date || Date.now()).toLocaleDateString()}`, 120, 45);
      doc.text(`Therapist: ${therapistName || 'Unknown Therapist'}`, 120, 52);
      
      doc.setDrawColor(203, 213, 225); // Slate 300
      doc.line(20, 58, 190, 58);
      
      // Content Sections
      let yPos = 70;
      const margin = 20;
      const maxLineWidth = 170;
      const lineHeight = 7;
      
      const addSection = (title, content) => {
        if (!content) return;
        
        // Check page break for title
        if (yPos > 270) {
          doc.addPage();
          yPos = 20;
        }
        
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(15, 23, 42); // Slate 900
        doc.text(title.toUpperCase(), margin, yPos);
        yPos += 8;
        
        doc.setFontSize(11);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(51, 65, 85); // Slate 700
        
        const textLines = doc.splitTextToSize(content, maxLineWidth);
        
        textLines.forEach(line => {
          if (yPos > 280) {
            doc.addPage();
            yPos = 20;
          }
          doc.text(line, margin, yPos);
          yPos += lineHeight;
        });
        
        yPos += 5; // Spacing after section
      };

      addSection('Subjective', soapData.subjective);
      addSection('Objective', soapData.objective);
      addSection('Assessment', soapData.assessment);
      addSection('Plan', soapData.plan);
      
      // Footer
      const pageCount = doc.internal.getNumberOfPages();
      for(let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184); // Slate 400
        doc.text(`Generated by Physiome AI Assistant - Page ${i} of ${pageCount}`, 20, 290);
      }
      
      const fileName = `SOAP_${(patientName || 'Patient').replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
      doc.save(fileName);
      
      toast.success('PDF exported successfully');
    } catch (error) {
      console.error('PDF Export Error:', error);
      toast.error('Failed to export PDF');
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <Button 
      variant="outline" 
      onClick={handleExport}
      disabled={isExporting}
      className="gap-2"
    >
      {isExporting ? (
        <Loader2 className="w-4 h-4 animate-spin" />
      ) : (
        <Download className="w-4 h-4" />
      )}
      Export PDF
    </Button>
  );
}
